# Generated by Django 4.2 on 2023-04-12 13:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='<small class="text-muted">CharField [1, 300]</small><hr><br>', max_length=300, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(300)], verbose_name='Название компании')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text='<small class="text-muted">CharField [1, 200]</small><hr><br>', max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(200)], verbose_name='Название вакансии')),
                ('salary', models.DecimalField(blank=True, decimal_places=3, default=1.0, help_text='<small class="text-muted">DecimalField [1, 999999999]</small><hr><br>', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999)], verbose_name='Зарплата')),
                ('experience', models.IntegerField(blank=True, default=0, help_text='<small class="text-muted">IntegerField [0, 30]</small><hr><br>', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Опыт')),
                ('work_type', models.CharField(blank=True, default='', help_text='<small class="text-muted">CharField [1, 50]</small><hr><br>', max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(50)], verbose_name='График работы')),
                ('description', models.TextField(blank=True, db_index=True, default='', error_messages=False, help_text='<small class="text-muted">TextField [0, 3000]</small><hr><br>', max_length=3000, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(3000)], verbose_name='Описание')),
                ('created', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, help_text='<small class="text-muted">DateTimeField</small><hr><br>', null=True, verbose_name='Дата и время создания')),
                ('company', models.ForeignKey(blank=True, default=None, error_messages=False, help_text='<small class="text-muted">ForeignKey</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_vacancies.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ('-created', 'title'),
            },
        ),
    ]
