# Generated by Django 4.2 on 2023-04-15 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_second', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tovar',
            name='slug',
        ),
    ]
