# Generated by Django 4.2 on 2023-04-17 13:17

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_second', '0002_remove_tovar_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('which_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_second.tovar')),
                ('who_commented', models.ForeignKey(on_delete=django.contrib.auth.models.User, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комментарий к товару',
                'verbose_name_plural': 'Комментарии к товару',
                'ordering': ('-date',),
            },
        ),
    ]
