# Generated by Django 4.2 on 2023-04-19 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_second', '0004_loggingmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoggingModel',
        ),
    ]
